name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start Shopping Store App
        run: |
          chmod +x './ShoppingStoreApp/shopping-store-linux-amd64'
          ./ShoppingStoreApp/shopping-store-linux-amd64 &

      - name: Run Cypress tests
        id: cypress-tests
        run: npm run cy:run:test
        if: always()

      - name: Upload Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

  download-artifacts:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: allure-results
