name: Cypress Tests

on: [push]

jobs:
  preconditions:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Save dependencies
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          if-no-files-found: error
          path: node_modules

  cypress-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: preconditions
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download node_modules folder
        uses: actions/download-artifact@v4
        with:
          name: node_modules

      - name: Start Shopping Store App
        run: |
          chmod +x './ShoppingStoreApp/shopping-store-linux-amd64'
          ./ShoppingStoreApp/shopping-store-linux-amd64 &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          start: npm run cy:run
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
