name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start Shopping Store App
        run: |
          chmod +x './ShoppingStoreApp/shopping-store-linux-amd64'
          ./ShoppingStoreApp/shopping-store-linux-amd64 &

      - name: Run Cypress tests
        id: cypress-tests
        run: npm run cy:run
        if: always()
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.containers }}
          path: allure-results

  download-reports:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          pattern: allure-results-*
          merge-multiple: true
      - run: ls -R allure-results
