name: Cypress Tests

on: [push]

jobs:
  prepare:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Create matrix
        id: prepare
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 5

      - name: Print result
        run: echo '${{ steps.prepare.outputs.matrix }}'

  tests:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print GitHub strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Start Shopping Store App
        run: |
          chmod +x './ShoppingStoreApp/shopping-store-linux-amd64'
          ./ShoppingStoreApp/shopping-store-linux-amd64 &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run cy:run
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
